tasks_file_path: "data/preprocessed/stock/dev/dev/tasks.pkl"
subset_file_path: null
db_root_dir: "data/stock/dev/dev_databases"
n_processes: 24
max_rollout_steps: 24
max_depth: 16
exploration_constant: 1.414
save_root_dir: "results/Qwen2.5-Coder-32B-Instruct/stock/dev"
mcts_model_kwargs:
    model: "Qwen2.5-32B-Instruct"
    n: 3
    top_p: 0.8
    max_tokens: 4096
    temperature: 0.8
    n_strategy: "single"
reward_model_kwargs: null
show_progress_log: true
visualize_tree: false